### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by lewisj4** [lewisj4/suite_solo_app#5]
@harimohanraj89 @DrRobotmck @williamfshaw @bigtone1284

User Story:
As a user, I want to be able to login to my account so that I can easily access my medical information

I am trying to log into a session with one of my users that I seeded into my db and I am getting back a 400 (Bad Request) with the bad request pointing to my password. I'm not quite sure why it is having a problem with the password though. I also tried going into the db, copying the password straight from there and putting it into the field if it was a spelling issue, but still got the 400 bad request error.

I've gone everywhere in my codebase where I thought the issue could be, made a couple tweaks, but I'm still getting the bad request error.

(Pushed code to my repo at 1:24 pm)

**Comment by DrRobotmck** [comment]
Something looks fishy in this bit of code...

```
userRouter.post('/sessions', function(req, res) {
    var loginUsername = req.body.username;
    var loginPassword = req.body.username;

    User
        .findOne({
            where: { username: loginUsername }
        })
        .then(function(user) {
            if (user) {
                var passwordDigest = user.password_digest;

                bcrypt.compare(loginPassword, passwordDigest, function(err, result) {
                    if (result) {
                        req.session.currentUser = user.id;
                        res.send('Correct Credentials');
                    } else {
                        res.status(400);
                        res.send({
                            err: 400,
                            msg: 'Sorry, you are not allowed access'
                        });
                    }
                });
            } else {
                res.status(400);
                res.send({
                    err: 400,
                    msg: 'Sorry, the username does not exist'
                });
            }
        });
});
```

**Comment by DrRobotmck** [comment]
@lewisj4

**Comment by DrRobotmck** [comment]
is this solved? @lewisj4

**Comment by lewisj4** [comment]
Nope, I'm separating my user login information from the users personal
information because of the information in the errors that I was getting.
You can close it if you want and if I have an issue down the road in the
next couple hours I'll submit another issue

On Thursday, April 23, 2015, McKenneth Scott III notifications@github.com
wrote:

> is this solved? @lewisj4 https://github.com/lewisj4
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lewisj4/suite_solo_app/issues/5#issuecomment-95683404
> .

## 

James Lewis
B.S. International Business
B.S. Marketing

**Comment by lewisj4** [comment]
Right, I caught the req.body.username where req.body.password should've
been and made that change, but still got errors

On Thursday, April 23, 2015, McKenneth Scott III notifications@github.com
wrote:

> is this solved? @lewisj4 https://github.com/lewisj4
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lewisj4/suite_solo_app/issues/5#issuecomment-95683404
> .

## 

James Lewis
B.S. International Business
B.S. Marketing

**Comment by DrRobotmck** [comment]
What are the new errors?

**Comment by lewisj4** [comment]
``` bash
Error Request: main: password_digest cannot be null
Possibly unhandled SequelizeValidationError: notNull Violation: password_digest cannot be null
    at /Users/jameslewis/WDI_main/suite_solo_app/node_modules/sequelize/lib/instance-validator.js:153:14
    at tryCatch1 (/Users/jameslewis/WDI_main/suite_solo_app/node_modules/sequelize/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler (/Users/jameslewis/WDI_main/suite_solo_app/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:571:13)
    at Promise._settlePromiseFromHandler (/Users/jameslewis/WDI_main/suite_solo_app/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAt (/Users/jameslewis/WDI_main/suite_solo_app/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:713:18)
    at Promise._settlePromiseAt (/Users/jameslewis/WDI_main/suite_solo_app/node_modules/sequelize/lib/promise.js:76:18)
    at Promise._settlePromises (/Users/jameslewis/WDI_main/suite_solo_app/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:854:14)
    at Async._consumeFunctionBuffer (/Users/jameslewis/WDI_main/suite_solo_app/node_modules/sequelize/node_modules/bluebird/js/main/async.js:85:12)
    at Async.consumeFunctionBuffer (/Users/jameslewis/WDI_main/suite_solo_app/node_modules/sequelize/node_modules/bluebird/js/main/async.js:40:14)
    at process._tickCallback (node.js:355:11)
```

For some reason it's never getting the password_digest, I was wondering because my seed file passwords aren't encrypted if that would be an issue?

**Comment by DrRobotmck** [comment]
make sure you format for code!

**Comment by lewisj4** [comment]
What exactly do you mean "format for code"?

**Comment by DrRobotmck** [comment]
That looks like an error that you might get when attempting to create a new user. Are you sure you are hitting the proper route? What routes does the server say are being hit? What type of data is coming through to the server? Have you tried console.log-ing some of the data on the client and server side?

re: 'format for code'- using backticks "```" to make your pasted code look pretty, like i fixed your previous comment.

**Comment by lewisj4** [comment]
```
userRouter.post('/sessions', function(req, res) {
    var loginUsername = req.body.username;
    var loginPassword = req.body.password;

    User
        .findOne({
            where: { username: loginUsername }
        })
        .then(function(user) {
            if (user) {
                var passwordDigest = user.password_digest;

                bcrypt.compare(loginPassword, passwordDigest, function(err, result) {
                    if (result) {
                        req.session.currentUser = user.id;
                        res.send('Correct Credentials');
                    } else {
                        res.status(400);
                        res.send({
                            err: 400,
                            msg: 'Sorry, bad password'
                        });
                    }
                });
            } else {
                res.status(400);
                res.send({
                    err: 400,
                    msg: 'Sorry, the username does not exist'
                });
            }
        });
});
```

That is the route being hit and it hits and takes the username field, but then gives a 400 for the password.

**Comment by DrRobotmck** [comment]
which 400 error are you getting?

**Comment by lewisj4** [comment]
'Sorry, bad password.' I was talking with Robert and I think it is because my db has an unencrypted password in it because I seeded my database with dummy data. Do you know if that would be the reason?

**Comment by DrRobotmck** [comment]
potentially if you are looking for a user with an unencrypted password

**Comment by lewisj4** [comment]
Okay, yah, I think that is the issue. Thanks mck I'll dig into my user creation route and calls so that i can create one and test that person out
